#ifndef UGLY_JSON_PARSER_CONSTANTS_INCLUDE_HEADER
#define UGLY_JSON_PARSER_CONSTANTS_INCLUDE_HEADER

#include "./Constants/ResultEnumConstants.hpp"

#endif // !UGLY_JSON_PARSER_CONSTANTS_INCLUDE_HEADER
